// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJuRTA_PIrGiZpTU_Q4x8d7zsGZdZaiBg',
    appId: '1:828215380964:web:a3355d053d1dc87da395f1',
    messagingSenderId: '828215380964',
    projectId: 'e-commerce-app-2f7f8',
    authDomain: 'e-commerce-app-2f7f8.firebaseapp.com',
    storageBucket: 'e-commerce-app-2f7f8.firebasestorage.app',
    measurementId: 'G-GNDR4DX4KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYAlYeqEeFkWAKD0P0I8E_uDP8Knw3_j8',
    appId: '1:828215380964:android:3977a64ed05c0211a395f1',
    messagingSenderId: '828215380964',
    projectId: 'e-commerce-app-2f7f8',
    storageBucket: 'e-commerce-app-2f7f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMUFU49tO1cA-X_-og9j7UB843Lmzm5g0',
    appId: '1:828215380964:ios:ba4db17d4c4ce598a395f1',
    messagingSenderId: '828215380964',
    projectId: 'e-commerce-app-2f7f8',
    storageBucket: 'e-commerce-app-2f7f8.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppApi26',
  );
}
